backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# Define where public images will be stored
media_folder: "public/images/uploads"

# CMS Content
collections:
  - name: "home-page"
    label: "Home Page"
    folder: "content/home-page"
    create: true
    fields:
      - {label: "Tab Title", name: "tab-title", widget: "string"}