backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# Define where public images will be stored
media_folder: "public/images/uploads"

extension: json

# CMS Content
collections:
  # Content for Web Pages
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home-page"
        file: "content/home-page.json"
        fields:
          - {label: "Tab Title", name: tab-title, widget: string}
          - {label: "Title", name: title, widget: string}
      - label: "Events Page"
        name: "events-page"
        file: "content/events-page.json"
        fields:
          - {label: "Tab Title", name: tab-title, widget: string}
          - {label: "Title", name: title, widget: string} 